import type { Grievance, ClusterSummary } from '../types/grievance';

export const INITIAL_GRIEVANCES: Grievance[] = [
  {
    Complaint_ID: 'G-1001',
    Complaint: 'Major water pipeline leak outside Shoppers Stop SV Road. Water gushing onto main road causing flooding and low pressure in homes.',
    Language: 'English',
    Department: 'Water Supply',
    Topic: 'Water Pipeline Leakage & Disruption',
    Severity: 5,
    Urgency: 4,
    Affected_Scope: 5,
    Priority_Score: 92,
    Priority: 'Critical',
    Duplicate_Group: 'DUP-CLUSTER-402',
    Ward: 'Ward 4 - Andheri West',
    Status: 'In Progress',
    Date_Submitted: '2026-08-15T08:30:00.000Z',
    Latitude: 19.1197,
    Longitude: 72.8464,
    Upvotes: 42,
    Assigned_Officer: 'Er. Rajesh Sharma (Nodal Water Dept)',
    Cluster_X: 18.4,
    Cluster_Y: 72.1,
  },
  {
    Complaint_ID: 'G-1002',
    Complaint: 'Ward 4 me SV road near Shoppers Stop paani ki pipe phat gayi hai. Puri sadak par paani bhara hua hai aur supply band hai.',
    Language: 'Hinglish',
    Department: 'Water Supply',
    Topic: 'Water Pipeline Leakage & Disruption',
    Severity: 5,
    Urgency: 5,
    Affected_Scope: 4,
    Priority_Score: 95,
    Priority: 'Critical',
    Duplicate_Group: 'DUP-CLUSTER-402',
    Ward: 'Ward 4 - Andheri West',
    Status: 'In Progress',
    Date_Submitted: '2026-08-15T09:15:00.000Z',
    Latitude: 19.1199,
    Longitude: 72.8468,
    Upvotes: 29,
    Assigned_Officer: 'Er. Rajesh Sharma (Nodal Water Dept)',
    Cluster_X: 19.1,
    Cluster_Y: 71.8,
  },
  {
    Complaint_ID: 'G-1003',
    Complaint: 'एंडहेरी वेस्ट वार्ड 4 में पिछले 24 घंटे से पीने का पानी नहीं आ रहा है। पाइपलाइन लीकेज की वजह से पूरी सोसाइटी परेशान है।',
    Language: 'Hindi',
    Department: 'Water Supply',
    Topic: 'Water Pipeline Leakage & Disruption',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 4,
    Priority_Score: 82,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-402',
    Ward: 'Ward 4 - Andheri West',
    Status: 'Pending',
    Date_Submitted: '2026-08-15T10:00:00.000Z',
    Latitude: 19.1205,
    Longitude: 72.8460,
    Upvotes: 18,
    Assigned_Officer: 'Er. Rajesh Sharma (Nodal Water Dept)',
    Cluster_X: 17.8,
    Cluster_Y: 73.0,
  },
  {
    Complaint_ID: 'G-1004',
    Complaint: 'Huge pothole on Link Road junction near Infiniti Mall. Multiple two-wheelers slipping during rain. Urgent repair needed before accidents.',
    Language: 'English',
    Department: 'Roads & Infra',
    Topic: 'Pothole & Road Surface Hazard',
    Severity: 4,
    Urgency: 5,
    Affected_Scope: 4,
    Priority_Score: 88,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-403',
    Ward: 'Ward 4 - Andheri West',
    Status: 'In Progress',
    Date_Submitted: '2026-08-14T14:20:00.000Z',
    Latitude: 19.1368,
    Longitude: 72.8312,
    Upvotes: 35,
    Assigned_Officer: 'Tech. Officer Amit Patil (Infra)',
    Cluster_X: 62.1,
    Cluster_Y: 34.5,
  },
  {
    Complaint_ID: 'G-1005',
    Complaint: 'Link Road Infiniti Mall ke paas bohot bada gadda hai. Bike riders falling down. Emergency pothole filling require hai.',
    Language: 'Hinglish',
    Department: 'Roads & Infra',
    Topic: 'Pothole & Road Surface Hazard',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 3,
    Priority_Score: 78,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-403',
    Ward: 'Ward 4 - Andheri West',
    Status: 'Pending',
    Date_Submitted: '2026-08-14T16:45:00.000Z',
    Latitude: 19.1365,
    Longitude: 72.8310,
    Upvotes: 14,
    Assigned_Officer: 'Tech. Officer Amit Patil (Infra)',
    Cluster_X: 63.5,
    Cluster_Y: 33.2,
  },
  {
    Complaint_ID: 'G-1006',
    Complaint: 'Massive garbage pile uncollected for 5 days near Bandra East Station East side exit. Severe foul smell and vector risk.',
    Language: 'English',
    Department: 'Sanitation & Waste',
    Topic: 'Garbage Dump Overflow & Waste Discard',
    Severity: 4,
    Urgency: 3,
    Affected_Scope: 4,
    Priority_Score: 72,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-701',
    Ward: 'Ward 7 - Bandra East',
    Status: 'Pending',
    Date_Submitted: '2026-08-15T06:10:00.000Z',
    Latitude: 19.0620,
    Longitude: 72.8480,
    Upvotes: 22,
    Assigned_Officer: 'Sanitation Sup. Suresh Kadam',
    Cluster_X: -45.2,
    Cluster_Y: 82.1,
  },
  {
    Complaint_ID: 'G-1007',
    Complaint: 'बांद्रा ईस्ट स्टेशन के बाहर कचरे का ढेर लगा हुआ है। 5 दिन से सफाई कर्मचारी नहीं आए हैं। मक्खियां और बदबू बढ़ गई है।',
    Language: 'Hindi',
    Department: 'Sanitation & Waste',
    Topic: 'Garbage Dump Overflow & Waste Discard',
    Severity: 3,
    Urgency: 3,
    Affected_Scope: 4,
    Priority_Score: 66,
    Priority: 'Medium',
    Duplicate_Group: 'DUP-CLUSTER-701',
    Ward: 'Ward 7 - Bandra East',
    Status: 'Pending',
    Date_Submitted: '2026-08-15T07:30:00.000Z',
    Latitude: 19.0624,
    Longitude: 72.8485,
    Upvotes: 16,
    Assigned_Officer: 'Sanitation Sup. Suresh Kadam',
    Cluster_X: -43.8,
    Cluster_Y: 83.5,
  },
  {
    Complaint_ID: 'G-1008',
    Complaint: 'Transformer blast near BKC Connector Road, Ward 7. Complete blackout in BKC block C since 2 hours. Sparks seen from pole.',
    Language: 'English',
    Department: 'Electricity',
    Topic: 'Transformer Failure & Blackout',
    Severity: 5,
    Urgency: 5,
    Affected_Scope: 5,
    Priority_Score: 98,
    Priority: 'Critical',
    Duplicate_Group: 'DUP-CLUSTER-709',
    Ward: 'Ward 7 - Bandra East',
    Status: 'Escalated',
    Date_Submitted: '2026-08-15T11:00:00.000Z',
    Latitude: 19.0660,
    Longitude: 72.8620,
    Upvotes: 56,
    Assigned_Officer: 'Chief Eng. Ramesh Verma (Power Grid)',
    Cluster_X: 85.0,
    Cluster_Y: -52.0,
  },
  {
    Complaint_ID: 'G-1009',
    Complaint: 'BKC me transformer se aag nikli aur ab püre area me light chali gayi hai. High voltage risk. Please send electrical emergency team.',
    Language: 'Hinglish',
    Department: 'Electricity',
    Topic: 'Transformer Failure & Blackout',
    Severity: 5,
    Urgency: 5,
    Affected_Scope: 4,
    Priority_Score: 94,
    Priority: 'Critical',
    Duplicate_Group: 'DUP-CLUSTER-709',
    Ward: 'Ward 7 - Bandra East',
    Status: 'Escalated',
    Date_Submitted: '2026-08-15T11:15:00.000Z',
    Latitude: 19.0664,
    Longitude: 72.8625,
    Upvotes: 31,
    Assigned_Officer: 'Chief Eng. Ramesh Verma (Power Grid)',
    Cluster_X: 86.5,
    Cluster_Y: -50.8,
  },
  {
    Complaint_ID: 'G-1010',
    Complaint: 'Senior citizen widow pension payout delayed for past 3 months in Kurla East PDS zone. Token submitted in June.',
    Language: 'English',
    Department: 'Public Distribution',
    Topic: 'Pension Disbursal & Benefit Delay',
    Severity: 3,
    Urgency: 3,
    Affected_Scope: 2,
    Priority_Score: 52,
    Priority: 'Medium',
    Duplicate_Group: null,
    Ward: 'Ward 12 - Kurla East',
    Status: 'Pending',
    Date_Submitted: '2026-08-13T10:00:00.000Z',
    Latitude: 19.0650,
    Longitude: 72.8790,
    Upvotes: 5,
    Assigned_Officer: 'PDS Inspector Sneha Kulkarni',
    Cluster_X: -78.0,
    Cluster_Y: -45.0,
  },
  {
    Complaint_ID: 'G-1011',
    Complaint: 'कुर्ला ईस्ट में बुजुर्गों की पेंशन पिछले 3 महीने से खाते में नहीं आई है। डीबीटी पोर्टल पर पेंडिंग दिखा रहा है।',
    Language: 'Hindi',
    Department: 'Public Distribution',
    Topic: 'Pension Disbursal & Benefit Delay',
    Severity: 3,
    Urgency: 4,
    Affected_Scope: 2,
    Priority_Score: 58,
    Priority: 'Medium',
    Duplicate_Group: null,
    Ward: 'Ward 12 - Kurla East',
    Status: 'In Progress',
    Date_Submitted: '2026-08-12T14:30:00.000Z',
    Latitude: 19.0655,
    Longitude: 72.8795,
    Upvotes: 8,
    Assigned_Officer: 'PDS Inspector Sneha Kulkarni',
    Cluster_X: -76.5,
    Cluster_Y: -46.2,
  },
  {
    Complaint_ID: 'G-1012',
    Complaint: 'Open stormwater drain overflowing near Malad West subway. Black sewage water mixing on pedestrian pathway.',
    Language: 'English',
    Department: 'Sanitation & Waste',
    Topic: 'Open Drain Blockage & Sewage Leak',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 4,
    Priority_Score: 80,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-205',
    Ward: 'Ward 2 - Malad West',
    Status: 'Pending',
    Date_Submitted: '2026-08-14T09:00:00.000Z',
    Latitude: 19.1860,
    Longitude: 72.8480,
    Upvotes: 19,
    Assigned_Officer: 'Sanitation Sup. Suresh Kadam',
    Cluster_X: -50.1,
    Cluster_Y: 76.4,
  },
  {
    Complaint_ID: 'G-1013',
    Complaint: 'Malad West subway side wala ganda naala overflow ho raha hai. Pedestrians cannot cross road without stepping in drain water.',
    Language: 'Hinglish',
    Department: 'Sanitation & Waste',
    Topic: 'Open Drain Blockage & Sewage Leak',
    Severity: 4,
    Urgency: 3,
    Affected_Scope: 3,
    Priority_Score: 71,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-205',
    Ward: 'Ward 2 - Malad West',
    Status: 'Pending',
    Date_Submitted: '2026-08-14T11:20:00.000Z',
    Latitude: 19.1864,
    Longitude: 72.8482,
    Upvotes: 12,
    Assigned_Officer: 'Sanitation Sup. Suresh Kadam',
    Cluster_X: -51.5,
    Cluster_Y: 77.8,
  },
  {
    Complaint_ID: 'G-1014',
    Complaint: 'Street lights non-functional for 1 km stretch on Dadar West Gokhale Road. Dark spot causing safety hazard for women commuters.',
    Language: 'English',
    Department: 'Electricity',
    Topic: 'Street Lighting & Dark Spot Hazard',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 3,
    Priority_Score: 76,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-902',
    Ward: 'Ward 9 - Dadar West',
    Status: 'In Progress',
    Date_Submitted: '2026-08-14T19:00:00.000Z',
    Latitude: 19.0220,
    Longitude: 72.8380,
    Upvotes: 27,
    Assigned_Officer: 'Elect. Insp. Vijay Shinde',
    Cluster_X: 72.0,
    Cluster_Y: -28.4,
  },
  {
    Complaint_ID: 'G-1015',
    Complaint: 'दादर वेस्ट गोखले रोड पर सभी स्ट्रीट लाइट रात में बंद रहती हैं। महिलाओं की सुरक्षा के लिए तुरंत लाइट सही करें।',
    Language: 'Hindi',
    Department: 'Electricity',
    Topic: 'Street Lighting & Dark Spot Hazard',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 3,
    Priority_Score: 76,
    Priority: 'High',
    Duplicate_Group: 'DUP-CLUSTER-902',
    Ward: 'Ward 9 - Dadar West',
    Status: 'Pending',
    Date_Submitted: '2026-08-14T20:30:00.000Z',
    Latitude: 19.0225,
    Longitude: 72.8385,
    Upvotes: 15,
    Assigned_Officer: 'Elect. Insp. Vijay Shinde',
    Cluster_X: 73.2,
    Cluster_Y: -27.1,
  },
  {
    Complaint_ID: 'G-1016',
    Complaint: 'Road cave-in near Kurla West CST Road corner following heavy rainfall. Traffic bottleneck created.',
    Language: 'English',
    Department: 'Roads & Infra',
    Topic: 'Pothole & Road Surface Hazard',
    Severity: 5,
    Urgency: 4,
    Affected_Scope: 4,
    Priority_Score: 86,
    Priority: 'High',
    Duplicate_Group: null,
    Ward: 'Ward 12 - Kurla East',
    Status: 'Resolved',
    Date_Submitted: '2026-08-11T12:00:00.000Z',
    Latitude: 19.0700,
    Longitude: 72.8750,
    Upvotes: 40,
    Assigned_Officer: 'Tech. Officer Amit Patil (Infra)',
    Cluster_X: 58.4,
    Cluster_Y: 41.2,
  },
  {
    Complaint_ID: 'G-1017',
    Complaint: 'Dirty yellowish water coming from tap in Ward 2 Malad West layout for last 3 days. Foul chemical smell.',
    Language: 'English',
    Department: 'Water Supply',
    Topic: 'Water Contamination & Quality',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 3,
    Priority_Score: 74,
    Priority: 'High',
    Duplicate_Group: null,
    Ward: 'Ward 2 - Malad West',
    Status: 'Pending',
    Date_Submitted: '2026-08-15T05:30:00.000Z',
    Latitude: 19.1820,
    Longitude: 72.8420,
    Upvotes: 11,
    Assigned_Officer: 'Er. Rajesh Sharma (Nodal Water Dept)',
    Cluster_X: 25.4,
    Cluster_Y: 62.1,
  },
  {
    Complaint_ID: 'G-1018',
    Complaint: 'Electricity bill received for month of July is Rs. 48,000 for 2BHK flat. Meter reading mistake by DISCOM contractor.',
    Language: 'English',
    Department: 'Electricity',
    Topic: 'Electricity Billing Discrepancy',
    Severity: 2,
    Urgency: 2,
    Affected_Scope: 1,
    Priority_Score: 32,
    Priority: 'Low',
    Duplicate_Group: null,
    Ward: 'Ward 4 - Andheri West',
    Status: 'In Progress',
    Date_Submitted: '2026-08-10T16:00:00.000Z',
    Latitude: 19.1250,
    Longitude: 72.8350,
    Upvotes: 3,
    Assigned_Officer: 'Elect. Insp. Vijay Shinde',
    Cluster_X: 42.0,
    Cluster_Y: -80.0,
  },
  {
    Complaint_ID: 'G-1019',
    Complaint: 'Ration shop #402 refusing biometric grain disbursal claiming server down. Queue of 80 people waiting in heat.',
    Language: 'English',
    Department: 'Public Distribution',
    Topic: 'Ration Shop Supply & Biometric Issue',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 3,
    Priority_Score: 75,
    Priority: 'High',
    Duplicate_Group: null,
    Ward: 'Ward 9 - Dadar West',
    Status: 'In Progress',
    Date_Submitted: '2026-08-15T08:00:00.000Z',
    Latitude: 19.0280,
    Longitude: 72.8420,
    Upvotes: 21,
    Assigned_Officer: 'PDS Inspector Sneha Kulkarni',
    Cluster_X: -65.0,
    Cluster_Y: -30.0,
  },
  {
    Complaint_ID: 'G-1020',
    Complaint: 'Illegal debris dumped near Mithi River bank in Ward 7 Bandra. Blocking rainwater outflow channel.',
    Language: 'English',
    Department: 'Sanitation & Waste',
    Topic: 'Garbage Dump Overflow & Waste Discard',
    Severity: 4,
    Urgency: 4,
    Affected_Scope: 4,
    Priority_Score: 82,
    Priority: 'High',
    Duplicate_Group: null,
    Ward: 'Ward 7 - Bandra East',
    Status: 'Pending',
    Date_Submitted: '2026-08-14T15:10:00.000Z',
    Latitude: 19.0680,
    Longitude: 72.8550,
    Upvotes: 33,
    Assigned_Officer: 'Sanitation Sup. Suresh Kadam',
    Cluster_X: -38.0,
    Cluster_Y: 74.0,
  }
];

export const INITIAL_CLUSTERS: ClusterSummary[] = [
  {
    id: 'DUP-CLUSTER-402',
    topic: 'Water Pipeline Leakage & Disruption',
    department: 'Water Supply',
    ward: 'Ward 4 - Andheri West',
    count: 3,
    avgPriority: 90,
    representativeText: 'Major water main burst outside Shoppers Stop SV Road flooding road and halting residential supply.',
    centerX: 18.4,
    centerY: 72.1,
    color: '#0284c7' // sky-600
  },
  {
    id: 'DUP-CLUSTER-403',
    topic: 'Pothole & Road Surface Hazard',
    department: 'Roads & Infra',
    ward: 'Ward 4 - Andheri West',
    count: 2,
    avgPriority: 83,
    representativeText: 'Deep pothole cluster on Link Road Infiniti Mall junction causing vehicular accidents during rain.',
    centerX: 62.8,
    centerY: 33.8,
    color: '#d97706' // amber-600
  },
  {
    id: 'DUP-CLUSTER-701',
    topic: 'Garbage Dump Overflow & Waste Discard',
    department: 'Sanitation & Waste',
    ward: 'Ward 7 - Bandra East',
    count: 2,
    avgPriority: 69,
    representativeText: 'Uncollected refuse heap outside Bandra East station exit rotting for 5 days.',
    centerX: -44.5,
    centerY: 82.8,
    color: '#16a34a' // green-600
  },
  {
    id: 'DUP-CLUSTER-709',
    topic: 'Transformer Failure & Blackout',
    department: 'Electricity',
    ward: 'Ward 7 - Bandra East',
    count: 2,
    avgPriority: 96,
    representativeText: 'Substation transformer spark & explosion causing complete power outage in BKC commercial block.',
    centerX: 85.8,
    centerY: -51.4,
    color: '#dc2626' // red-600
  },
  {
    id: 'DUP-CLUSTER-205',
    topic: 'Open Drain Blockage & Sewage Leak',
    department: 'Sanitation & Waste',
    ward: 'Ward 2 - Malad West',
    count: 2,
    avgPriority: 75,
    representativeText: 'Stormwater drain backing up onto Malad subway pedestrian walkway.',
    centerX: -50.8,
    centerY: 77.1,
    color: '#059669' // emerald-600
  },
  {
    id: 'DUP-CLUSTER-902',
    topic: 'Street Lighting & Dark Spot Hazard',
    department: 'Electricity',
    ward: 'Ward 9 - Dadar West',
    count: 2,
    avgPriority: 76,
    representativeText: 'Multiple consecutive streetlights unlit on Gokhale Road causing dark safety hazards.',
    centerX: 72.6,
    centerY: -27.8,
    color: '#9333ea' // purple-600
  }
];

export const WARDS_LIST = [
  'Ward 4 - Andheri West',
  'Ward 7 - Bandra East',
  'Ward 2 - Malad West',
  'Ward 9 - Dadar West',
  'Ward 12 - Kurla East'
];

export const DEPARTMENTS_LIST: Array<Grievance['Department']> = [
  'Water Supply',
  'Roads & Infra',
  'Sanitation & Waste',
  'Electricity',
  'Public Distribution',
  'Public Health & Healthcare'
];

export const INITIAL_CIVIC_ISSUES: import('../types/grievance').CivicIssue[] = [
  {
    id: 'CI-1042',
    issue_title: 'Water Pipeline Leakage & Disruption near Andheri West',
    issue_description: 'Major municipal water pipeline leak outside Shoppers Stop SV Road causing road flooding, water wastage, and severe low pressure across Ward 4 homes.',
    category: 'Water Supply',
    subcategory: 'Water Pipeline Leakage & Disruption',
    ward: 'Ward 4 - Andheri West',
    latitude: 19.1197,
    longitude: 72.8464,
    status: 'In Progress',
    created_at: '2026-08-15T08:30:00.000Z',
    last_reported_at: '2026-08-20T10:15:00.000Z',
    affected_citizen_count: 89,
    report_count: 3,
    duplicate_count: 2,
    priority_score: 94,
    priority_level: 'Critical',
    severity_score: 5,
    urgency_score: 5,
    scope_score: 5,
    responsible_department: 'Water Supply',
    responsible_authority: 'Er. Rajesh Sharma (Nodal Water Dept)',
    cluster_confidence: 0.95,
    growth_rate: 152,
    is_emerging: true
  },
  {
    id: 'CI-1043',
    issue_title: 'Road Potholes & Surface Hazard near Link Road Junction',
    issue_description: 'Multiple deep potholes on Link Road junction near Infiniti Mall causing traffic jams, vehicle damage, and high accident risk during rain.',
    category: 'Roads & Infra',
    subcategory: 'Pothole & Road Surface Hazard',
    ward: 'Ward 4 - Andheri West',
    latitude: 19.1368,
    longitude: 72.8312,
    status: 'In Progress',
    created_at: '2026-08-14T14:20:00.000Z',
    last_reported_at: '2026-08-19T18:00:00.000Z',
    affected_citizen_count: 45,
    report_count: 2,
    duplicate_count: 1,
    priority_score: 88,
    priority_level: 'High',
    severity_score: 4,
    urgency_score: 5,
    scope_score: 4,
    responsible_department: 'Roads & Infra',
    responsible_authority: 'Tech. Officer Amit Patil (Infra)',
    cluster_confidence: 0.91,
    growth_rate: 85,
    is_emerging: false
  },
  {
    id: 'CI-1044',
    issue_title: 'Garbage Accumulation & Waste Overflow near Station Area',
    issue_description: 'Uncollected garbage heap outside station area overflowing onto pedestrian footpath, causing severe odor, flies, and public sanitation hazard.',
    category: 'Sanitation & Waste',
    subcategory: 'Garbage Heap Overflow & Waste Discard',
    ward: 'Ward 7 - Bandra East',
    latitude: 19.0620,
    longitude: 72.8480,
    status: 'Escalated',
    created_at: '2026-08-10T09:00:00.000Z',
    last_reported_at: '2026-08-20T12:00:00.000Z',
    affected_citizen_count: 112,
    report_count: 4,
    duplicate_count: 3,
    priority_score: 96,
    priority_level: 'Critical',
    severity_score: 5,
    urgency_score: 5,
    scope_score: 5,
    responsible_department: 'Sanitation & Waste',
    responsible_authority: 'Sanitation Inspector Suresh Kulkarni',
    cluster_confidence: 0.94,
    growth_rate: 210,
    is_emerging: true
  },
  {
    id: 'CI-1045',
    issue_title: 'Transformer Sparking & High Voltage Outage near SV Road',
    issue_description: 'Electricity distribution transformer sparking heavily and tripping power across commercial blocks in Malad West.',
    category: 'Electricity',
    subcategory: 'Transformer Failure & Blackout',
    ward: 'Ward 2 - Malad West',
    latitude: 19.1860,
    longitude: 72.8485,
    status: 'Pending',
    created_at: '2026-08-18T11:45:00.000Z',
    last_reported_at: '2026-08-20T08:30:00.000Z',
    affected_citizen_count: 64,
    report_count: 2,
    duplicate_count: 1,
    priority_score: 92,
    priority_level: 'Critical',
    severity_score: 5,
    urgency_score: 5,
    scope_score: 4,
    responsible_department: 'Electricity',
    responsible_authority: 'Electrical Chief V. M. Deshmukh',
    cluster_confidence: 0.89,
    growth_rate: 130,
    is_emerging: true
  },
  {
    id: 'CI-1046',
    issue_title: 'Hospital Emergency Ward Infrastructure & ICU Bed Delay',
    issue_description: 'Civil hospital emergency ward reporting critical shortage of working oxygen meters and delayed ICU bed allocation.',
    category: 'Public Health & Healthcare',
    subcategory: 'Hospital Infrastructure & Emergency Services',
    ward: 'Ward 9 - Dadar West',
    latitude: 19.0178,
    longitude: 72.8478,
    status: 'In Progress',
    created_at: '2026-08-16T16:10:00.000Z',
    last_reported_at: '2026-08-19T14:20:00.000Z',
    affected_citizen_count: 38,
    report_count: 2,
    duplicate_count: 1,
    priority_score: 84,
    priority_level: 'High',
    severity_score: 4,
    urgency_score: 4,
    scope_score: 4,
    responsible_department: 'Public Health & Healthcare',
    responsible_authority: 'Dr. Sunita Rao (Chief Health Officer)',
    cluster_confidence: 0.92,
    growth_rate: 45,
    is_emerging: false
  }
];

